# server config
server:
  port: 8018
  
# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##WATER
    password: WATER
<<<<<<< HEAD
<<<<<<< HEAD

  
  # mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
=======
=======
>>>>>>> d4d2e193517ba0a5342894b3e67a892cac5ba8f6
# file upload config


# image upload directory

      
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
<<<<<<< HEAD
  

  
  
>>>>>>> 050701942f800ee90f0038deb4fd3a95ff95d049
  
  
  
  
  
  
  
=======
>>>>>>> d4d2e193517ba0a5342894b3e67a892cac5ba8f6
