# server config
server:
  port: 8018
  
# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##WATER
    password: WATER
# file upload config

<<<<<<< HEAD
=======

# image upload directory

      
# mybatis config

  

>>>>>>> 9738d958d9032afa2cae672a675d821e857ca262
  
  
  
  
  
  
  